# -*- coding: utf-8 -*-
"""Personalizado Scrape-PlayStore.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jfspo-YoRezxsDAOwsStxpbxTrAKWE4o

### Librerías que necesitamos
####-google-play-scraper
####-pandas
####-numpy
"""

#Si no tenemos instalada la librería de google-play-scraper, la instalamos mediante el siguiente comando:
# !pip install google-play-scraper

import numpy as np
import pandas as pd

from google_play_scraper import Sort, reviews_all, reviews

"""## Código de scraping

###Scraping de las reviews
"""

result = reviews_all(
    'appinventor.ai_ruizrube.Fraseologia',
    sleep_milliseconds=0, # por defecto a 0
    lang='es',            # por defecto en 'en'
    country='es',         # por defecto en 'us'
    sort=Sort.NEWEST,     # por defecto en Sort.MOST_RELEVANT, pero podemos usar Sort.NEWEST para obtener las más recientes
)

"""###Scraping de las valoraciones"""

result, continuation_token = reviews(
    'com.facebook.katana',
    lang='id',                # por defecto en 'en'
    country='id',             # por defecto en 'us'
    sort=Sort.MOST_RELEVANT,  # por defecto en Sort.MOST_RELEVANT, pero podemos usar Sort.NEWEST para obtener las más recientes
    count=500,               # por defecto 100
    filter_score_with=None    # por defecto a None (todas las puntuaciones). Podemos usar 1 2 3 4 5 para seleccionar una puntuación en concreto
)

"""##Resultados del scraping

###Código para previsualizar datos
"""

scrapeddata = pd.DataFrame(np.array(result),columns=['review'])

scrapeddata = scrapeddata.join(pd.DataFrame(scrapeddata.pop('review').tolist()))

scrapeddata.head()

"""### Código para ver el conteo de datos que tenemos:"""

len(scrapeddata.index)

"""###Filtrando los datos del scraping"""

scrapeddata[['content','score','at']].head()

"""###Código para ordenar por fechas"""

scrappeddata1 = scrapeddata[['content','score','at']]
sorteddata = scrappeddata1.sort_values(by='at', ascending=False) #Ordenado por más nuevos
sorteddata.head()

"""##Código para exportar nuestros datos del scraping"""

# sorteddata.to_excel("playstorescrapping.xlsx", index = False)  #Guardamos el archivo como XLSX. Para descargarlo, clicamos en la carpeta de archivos de la izquierda.
#
# sorteddata.to_csv("playstorescrapping.csv", index = False)  #Guardamos el archivo como CSV. Para descargarlo, clicamos en la carpeta de archivos de la izquierda.